export const FL_SUBURBS: string[] = [
  // Miami-Dade
  "Miami FL", "Downtown Miami FL", "Brickell FL", "Wynwood FL",
  "Midtown Miami FL", "Edgewater FL", "Design District FL",
  "Little Havana FL", "Little Haiti FL", "Allapattah FL",
  "Overtown FL", "Downtown Miami FL", "Miami Beach FL",
  "South Beach FL", "Mid-Beach FL", "North Beach FL",
  "Surfside FL", "Bal Harbour FL", "Bay Harbor Islands FL",
  "Indian Creek FL", "Sunny Isles Beach FL", "Aventura FL",
  "Hallandale Beach FL", "Hollywood FL", "Dania Beach FL",
  "Coral Gables FL", "Coconut Grove FL", "Pinecrest FL",
  "South Miami FL", "Kendall FL", "Doral FL",
  "Sweetwater FL", "Fontainebleau FL", "Westchester FL",
  "Hialeah FL", "Hialeah Gardens FL", "Miami Lakes FL",
  "Opa-locka FL", "North Miami FL", "North Miami Beach FL",
  "Biscayne Park FL", "El Portal FL", "Miami Shores FL",
  "Miami Springs FL", "Virginia Gardens FL",
  "Cutler Bay FL", "Palmetto Bay FL", "Perrine FL",
  "Homestead FL", "Florida City FL", "Key Biscayne FL",
  // Broward
  "Fort Lauderdale FL", "Downtown Fort Lauderdale FL",
  "Las Olas FL", "Flagler Village FL", "Victoria Park FL",
  "Wilton Manors FL", "Oakland Park FL", "Lauderdale Lakes FL",
  "Plantation FL", "Sunrise FL", "Weston FL",
  "Cooper City FL", "Davie FL", "Southwest Ranches FL",
  "Pembroke Pines FL", "Miramar FL", "Pompano Beach FL",
  "Deerfield Beach FL", "Margate FL", "Coconut Creek FL",
  "Coral Springs FL", "Parkland FL", "Tamarac FL",
  "North Lauderdale FL", "Lauderhill FL",
  // Palm Beach
  "West Palm Beach FL", "Downtown West Palm Beach FL",
  "Lake Worth Beach FL", "Lantana FL", "Boynton Beach FL",
  "Delray Beach FL", "Boca Raton FL", "Palm Beach FL",
  "Palm Beach Gardens FL", "Jupiter FL", "Riviera Beach FL",
  "Greenacres FL", "Royal Palm Beach FL", "Wellington FL",
  "Loxahatchee FL",
  // Orlando Metro
  "Orlando FL", "Downtown Orlando FL", "Thornton Park FL",
  "College Park Orlando FL", "Winter Park FL", "Maitland FL",
  "Altamonte Springs FL", "Longwood FL", "Lake Mary FL",
  "Sanford FL", "Kissimmee FL", "Celebration FL", "Buena Ventura Lakes FL",
  "St. Cloud FL", "Osceola County FL",
  "Ocoee FL", "Winter Garden FL", "Windermere FL",
  "Apopka FL", "Mount Dora FL",
  // Tampa Bay
  "Tampa FL", "Downtown Tampa FL", "Hyde Park Tampa FL",
  "Ybor City FL", "Seminole Heights FL", "Channelside FL",
  "Harbour Island FL", "Davis Islands FL", "South Tampa FL",
  "Westshore FL", "Carrollwood FL", "Temple Terrace FL",
  "New Tampa FL", "Brandon FL", "Riverview FL",
  "St. Petersburg FL", "Downtown St. Petersburg FL",
  "Old Northeast FL", "Kenwood FL", "Gulfport FL",
  "Clearwater FL", "Safety Harbor FL", "Dunedin FL",
  "Palm Harbor FL", "Tarpon Springs FL", "New Port Richey FL",
  "Land O'Lakes FL", "Wesley Chapel FL", "Lutz FL",
  "Sarasota FL", "Downtown Sarasota FL", "Siesta Key FL",
  "Longboat Key FL", "North Port FL", "Venice FL", "Nokomis FL",
  "Port Charlotte FL", "Punta Gorda FL", "Cape Coral FL",
  "Fort Myers FL", "Bonita Springs FL", "Naples FL",
  "Marco Island FL",
  // Jacksonville
  "Jacksonville FL", "Downtown Jacksonville FL",
  "San Marco FL", "Riverside FL", "Avondale FL",
  "Springfield FL", "Murray Hill FL", "Ortega FL",
  "Mandarin FL", "Southside FL", "Baymeadows FL",
  "Ponte Vedra Beach FL", "Jacksonville Beach FL",
  "Neptune Beach FL", "Atlantic Beach FL",
  "Fernandina Beach FL", "Amelia Island FL",
  // Other cities
  "Gainesville FL", "Ocala FL", "Tallahassee FL",
  "Pensacola FL", "Destin FL", "Panama City FL",
  "Fort Walton Beach FL", "Niceville FL",
  "Daytona Beach FL", "Port Orange FL", "Ormond Beach FL",
  "Palm Coast FL", "St. Augustine FL", "Flagler Beach FL",
  "Melbourne FL", "Palm Bay FL", "Cocoa FL", "Titusville FL",
  "Stuart FL", "Port St. Lucie FL", "Fort Pierce FL",
  "Vero Beach FL", "Sebastian FL",
  "Lakeland FL", "Winter Haven FL",
];
