// Greater Sydney suburbs — crawled in order
export const SYDNEY_SUBURBS = [
  "Manly NSW", "Bondi NSW", "Surry Hills NSW", "Chatswood NSW",
  "Newtown NSW", "Glebe NSW", "Pyrmont NSW", "Ultimo NSW",
  "Darlinghurst NSW", "Potts Point NSW", "Elizabeth Bay NSW", "Kings Cross NSW",
  "Paddington NSW", "Woollahra NSW", "Double Bay NSW", "Rose Bay NSW",
  "Vaucluse NSW", "Watsons Bay NSW", "Edgecliff NSW", "Rushcutters Bay NSW",
  "Balmain NSW", "Rozelle NSW", "Leichhardt NSW", "Annandale NSW",
  "Camperdown NSW", "Redfern NSW", "Waterloo NSW", "Zetland NSW",
  "Rosebery NSW", "Alexandria NSW", "Beaconsfield NSW", "Erskineville NSW",
  "St Peters NSW", "Sydenham NSW", "Marrickville NSW", "Dulwich Hill NSW",
  "Petersham NSW", "Summer Hill NSW", "Ashfield NSW", "Burwood NSW",
  "Croydon NSW", "Strathfield NSW", "Homebush NSW", "Concord NSW",
  "Rhodes NSW", "Meadowbank NSW", "Ryde NSW", "Gladesville NSW",
  "Hunters Hill NSW", "Lane Cove NSW", "Longueville NSW", "Northwood NSW",
  "Artarmon NSW", "St Leonards NSW", "Crows Nest NSW", "North Sydney NSW",
  "Kirribilli NSW", "Milsons Point NSW", "Lavender Bay NSW", "McMahons Point NSW",
  "Neutral Bay NSW", "Cremorne NSW", "Mosman NSW", "Spit Junction NSW",
  "Balmoral NSW", "Dee Why NSW", "Collaroy NSW", "Narrabeen NSW",
  "Avalon Beach NSW", "Newport NSW", "Mona Vale NSW", "Terrey Hills NSW",
  "Forestville NSW", "Frenchs Forest NSW", "Belrose NSW", "Davidson NSW",
  "Gordon NSW", "Killara NSW", "Lindfield NSW", "Roseville NSW",
  "Turramurra NSW", "Wahroonga NSW", "Pymble NSW", "St Ives NSW",
  "Hornsby NSW", "Waitara NSW", "Beecroft NSW", "Cheltenham NSW",
  "Epping NSW", "Eastwood NSW", "Rydalmere NSW", "Parramatta NSW",
  "Westmead NSW", "Granville NSW", "Harris Park NSW", "Merrylands NSW",
  "Guildford NSW", "Fairfield NSW", "Liverpool NSW", "Campbelltown NSW",
  "Hurstville NSW", "Kogarah NSW", "Rockdale NSW", "Arncliffe NSW",
  "Wolli Creek NSW", "Mascot NSW", "Botany NSW", "Maroubra NSW",
  "Coogee NSW", "Randwick NSW", "Kensington NSW", "Kingsford NSW",
  "Eastlakes NSW", "Daceyville NSW", "Hillsdale NSW", "Chifley NSW",
  "Little Bay NSW", "Malabar NSW", "La Perouse NSW", "Cronulla NSW",
  "Miranda NSW", "Caringbah NSW", "Sutherland NSW", "Engadine NSW",
];
