export const NY_SUBURBS: string[] = [
  // Manhattan
  "Manhattan NY", "Financial District NY", "Tribeca NY", "SoHo NY",
  "NoHo NY", "Little Italy NY", "Chinatown NY", "Lower East Side NY",
  "East Village NY", "West Village NY", "Greenwich Village NY",
  "Chelsea NY", "Hell's Kitchen NY", "Midtown NY", "Midtown East NY",
  "Murray Hill NY", "Kips Bay NY", "Gramercy Park NY", "Flatiron NY",
  "Union Square NY", "NoMad NY", "Hudson Yards NY",
  "Upper West Side NY", "Lincoln Square NY", "Morningside Heights NY",
  "Washington Heights NY", "Inwood NY",
  "Upper East Side NY", "Lenox Hill NY", "Yorkville NY", "Carnegie Hill NY",
  "East Harlem NY", "Harlem NY", "Central Harlem NY",
  "Marble Hill NY",
  // Brooklyn
  "Brooklyn NY", "Downtown Brooklyn NY", "DUMBO NY", "Brooklyn Heights NY",
  "Boerum Hill NY", "Cobble Hill NY", "Carroll Gardens NY", "Gowanus NY",
  "Red Hook NY", "Park Slope NY", "Windsor Terrace NY", "Prospect Park South NY",
  "Flatbush NY", "Prospect-Lefferts Gardens NY", "Crown Heights NY",
  "Bedford-Stuyvesant NY", "Bushwick NY", "Williamsburg NY",
  "East Williamsburg NY", "Greenpoint NY",
  "Fort Greene NY", "Clinton Hill NY", "Prospect Heights NY",
  "Sunset Park NY", "Borough Park NY", "Bensonhurst NY", "Bay Ridge NY",
  "Dyker Heights NY", "Bath Beach NY", "Gravesend NY", "Sheepshead Bay NY",
  "Brighton Beach NY", "Coney Island NY", "Sea Gate NY",
  "Flatlands NY", "Canarsie NY", "East New York NY", "Brownsville NY",
  "Cypress Hills NY", "Ocean Hill NY",
  "Fort Hamilton NY", "Midwood NY", "Kensington NY", "Ditmas Park NY",
  "Marine Park NY", "Mill Basin NY", "Bergen Beach NY",
  // Queens
  "Queens NY", "Long Island City NY", "Astoria NY", "Sunnyside NY",
  "Woodside NY", "Jackson Heights NY", "Elmhurst NY", "Corona NY",
  "Rego Park NY", "Forest Hills NY", "Kew Gardens NY", "Richmond Hill NY",
  "Ozone Park NY", "Howard Beach NY", "Broad Channel NY",
  "Flushing NY", "Whitestone NY", "College Point NY", "Murray Hill Queens NY",
  "Jamaica NY", "Jamaica Estates NY", "Hollis NY", "Queens Village NY",
  "Bayside NY", "Douglaston NY", "Little Neck NY", "Fresh Meadows NY",
  "Hillcrest NY", "Oakland Gardens NY", "Glen Oaks NY", "Bellerose NY",
  "Cambria Heights NY", "St. Albans NY", "South Ozone Park NY",
  "Springfield Gardens NY", "Rosedale NY", "Laurelton NY",
  "Rockaway Beach NY", "Far Rockaway NY", "Arverne NY",
  "Woodhaven NY", "Glendale NY", "Middle Village NY", "Maspeth NY",
  // Bronx
  "Bronx NY", "Mott Haven NY", "Melrose NY", "Morrisania NY",
  "Hunts Point NY", "Longwood NY", "Highbridge NY", "Concourse NY",
  "Fordham NY", "Belmont NY", "Tremont NY", "Mount Hope NY",
  "University Heights NY", "Morris Heights NY", "Kingsbridge NY",
  "Riverdale NY", "Spuyten Duyvil NY", "Van Cortlandt Village NY",
  "Norwood NY", "Williamsbridge NY", "Woodlawn NY", "Wakefield NY",
  "Pelham Bay NY", "Country Club NY", "City Island NY",
  "Throgs Neck NY", "Parkchester NY", "Castle Hill NY",
  "Soundview NY", "Clason Point NY", "Westchester Square NY",
  // Staten Island
  "Staten Island NY", "St. George NY", "Tompkinsville NY", "Stapleton NY",
  "Clifton NY", "Rosebank NY", "West Brighton NY", "New Brighton NY",
  "Castleton Corners NY", "Bulls Head NY", "New Springville NY",
  "Graniteville NY", "Port Richmond NY", "Mariners Harbor NY",
  "Tottenville NY", "Great Kills NY", "Eltingville NY", "Annadale NY",
  "Huguenot NY", "Rossville NY", "Charleston NY", "Richmond Valley NY",
  "Woodrow NY", "Oakwood NY", "Midland Beach NY", "South Beach NY",
  // Long Island
  "Hempstead NY", "Garden City NY", "Mineola NY", "Garden City Park NY",
  "Westbury NY", "New Hyde Park NY", "Floral Park NY", "Elmont NY",
  "Valley Stream NY", "Lynbrook NY", "Rockville Centre NY", "Malverne NY",
  "Freeport NY", "Baldwin NY", "Oceanside NY", "Island Park NY",
  "Long Beach NY", "Atlantic Beach NY",
  "Great Neck NY", "Port Washington NY", "Manhasset NY", "Roslyn NY",
  "Oyster Bay NY", "Huntington NY", "Northport NY", "Commack NY",
  "Smithtown NY", "Hauppauge NY", "Melville NY", "Farmingdale NY",
  "Levittown NY", "Hicksville NY", "Plainview NY", "Syosset NY",
  "Jericho NY", "Bethpage NY", "Massapequa NY", "Massapequa Park NY",
  "Amityville NY", "Lindenhurst NY", "Copiague NY", "Copiague NY",
  "East Meadow NY", "Uniondale NY", "Roosevelt NY",
  "Islip NY", "Bay Shore NY", "Brentwood NY", "Central Islip NY",
  "Ronkonkoma NY", "Patchogue NY", "Sayville NY",
  "Riverhead NY", "Southampton NY", "East Hampton NY",
  // Westchester
  "Yonkers NY", "New Rochelle NY", "Mount Vernon NY", "White Plains NY",
  "Scarsdale NY", "Bronxville NY", "Pelham NY", "Larchmont NY",
  "Mamaroneck NY", "Rye NY", "Port Chester NY", "Greenwich CT border NY",
  "Tarrytown NY", "Ossining NY", "Peekskill NY", "Cortlandt NY",
  "Hastings-on-Hudson NY", "Dobbs Ferry NY", "Ardsley NY",
  // Upstate
  "Albany NY", "Troy NY", "Schenectady NY", "Saratoga Springs NY",
  "Buffalo NY", "Amherst NY", "Cheektowaga NY", "Tonawanda NY",
  "Niagara Falls NY", "Lockport NY",
  "Rochester NY", "Greece NY", "Irondequoit NY", "Henrietta NY",
  "Syracuse NY", "Liverpool NY", "Cicero NY",
  "Binghamton NY", "Johnson City NY", "Endicott NY",
  "Utica NY", "Rome NY", "Ithaca NY", "Elmira NY",
  "Poughkeepsie NY", "Newburgh NY", "Kingston NY",
  "Middletown NY", "Orange County NY",
];
