export const TX_SUBURBS: string[] = [
  // Houston Metro
  "Houston TX", "Downtown Houston TX", "Midtown Houston TX",
  "Montrose TX", "Museum District TX", "Midtown TX",
  "Heights TX", "Garden Oaks TX", "Oak Forest TX",
  "Spring Branch TX", "Memorial TX", "Energy Corridor TX",
  "Westheimer TX", "Galleria TX", "Uptown Houston TX",
  "Greenway Plaza TX", "Upper Kirby TX", "Rice Military TX",
  "River Oaks TX", "Southampton TX", "West University Place TX",
  "Bellaire TX", "Meyerland TX", "Braeswood TX",
  "Third Ward TX", "Fourth Ward TX", "Midtown TX",
  "EaDo TX", "East End TX",
  "Clear Lake TX", "Pearland TX", "Friendswood TX",
  "Pasadena TX", "La Porte TX", "League City TX",
  "Webster TX", "Seabrook TX", "Kemah TX",
  "Sugar Land TX", "Missouri City TX", "Stafford TX",
  "Richmond TX", "Rosenberg TX",
  "Katy TX", "Cinco Ranch TX", "Cypress TX",
  "Spring TX", "The Woodlands TX", "Conroe TX",
  "Kingwood TX", "Humble TX", "Atascocita TX",
  "Baytown TX", "La Marque TX", "Texas City TX",
  // Dallas-Fort Worth
  "Dallas TX", "Downtown Dallas TX", "Uptown Dallas TX",
  "Oak Lawn TX", "Knox-Henderson TX", "Lower Greenville TX",
  "East Dallas TX", "Lakewood TX", "Lakewood Heights TX",
  "M Streets TX", "White Rock Lake TX",
  "Deep Ellum TX", "Bishop Arts TX", "Oak Cliff TX",
  "South Dallas TX", "Pleasant Grove TX",
  "North Dallas TX", "Preston Hollow TX", "University Park TX",
  "Highland Park TX", "Park Cities TX",
  "Las Colinas TX", "Irving TX", "Grand Prairie TX",
  "Fort Worth TX", "Downtown Fort Worth TX", "Sundance Square TX",
  "Near Southside TX", "Magnolia Avenue TX",
  "Haltom City TX", "Richland Hills TX", "North Richland Hills TX",
  "Keller TX", "Southlake TX", "Grapevine TX", "Colleyville TX",
  "Euless TX", "Bedford TX", "Hurst TX",
  "Plano TX", "McKinney TX", "Allen TX", "Frisco TX",
  "Prosper TX", "Celina TX", "Carrollton TX", "Addison TX",
  "Richardson TX", "Garland TX", "Mesquite TX", "Rowlett TX",
  "Sachse TX", "Wylie TX", "Rockwall TX", "Forney TX",
  "Denton TX", "Lewisville TX", "Flower Mound TX", "Coppell TX",
  "Mansfield TX", "Arlington TX", "Midlothian TX",
  "Duncanville TX", "DeSoto TX", "Cedar Hill TX", "Lancaster TX",
  // Austin Metro
  "Austin TX", "Downtown Austin TX", "East Austin TX",
  "South Congress TX", "South Lamar TX", "Bouldin Creek TX",
  "Travis Heights TX", "Barton Hills TX",
  "Hyde Park TX", "The Drag TX", "West Campus TX",
  "Clarksville TX", "Old West Austin TX", "Tarrytown TX",
  "Westlake Hills TX", "Rollingwood TX",
  "Mueller TX", "Windsor Park TX", "Cherrywood TX",
  "Riverside TX", "Montopolis TX", "Pleasant Valley TX",
  "North Loop TX", "Crestview TX", "Brentwood TX",
  "North Shoal Creek TX", "Allandale TX",
  "Round Rock TX", "Cedar Park TX", "Leander TX", "Georgetown TX",
  "Pflugerville TX", "Manor TX", "Elgin TX",
  "Kyle TX", "Buda TX", "San Marcos TX",
  // San Antonio
  "San Antonio TX", "Downtown San Antonio TX", "King William TX",
  "Southtown TX", "Monte Vista TX", "Alamo Heights TX",
  "Terrell Hills TX", "Olmos Park TX", "Castle Hills TX",
  "Hollywood Park TX", "Shavano Park TX",
  "Stone Oak TX", "North Central San Antonio TX",
  "Helotes TX", "Boerne TX", "Bulverde TX",
  "New Braunfels TX", "Schertz TX", "Cibolo TX",
  "Universal City TX", "Converse TX", "Selma TX",
  "Live Oak TX", "Windcrest TX",
  // Other major cities
  "El Paso TX", "Lubbock TX", "Amarillo TX",
  "Wichita Falls TX", "Abilene TX", "Tyler TX", "Longview TX",
  "Waco TX", "Temple TX", "Killeen TX", "Harker Heights TX",
  "College Station TX", "Bryan TX",
  "Midland TX", "Odessa TX",
  "Laredo TX", "McAllen TX", "Edinburg TX", "Mission TX",
  "Pharr TX", "Brownsville TX", "Corpus Christi TX",
  "Beaumont TX", "Port Arthur TX",
];
