export const CA_SUBURBS: string[] = [
  // Los Angeles City
  "Downtown Los Angeles CA", "Hollywood CA", "West Hollywood CA",
  "Silver Lake CA", "Echo Park CA", "Los Feliz CA", "Atwater Village CA",
  "Eagle Rock CA", "Highland Park CA", "Glassell Park CA",
  "Koreatown CA", "Mid-Wilshire CA", "Hancock Park CA",
  "Larchmont CA", "Fairfax CA", "West Adams CA", "Leimert Park CA",
  "Crenshaw CA", "Hyde Park CA", "Vermont-Slauson CA",
  "Boyle Heights CA", "East Los Angeles CA", "El Sereno CA",
  "City Terrace CA", "Lincoln Heights CA", "Cypress Park CA",
  "Mt Washington CA", "Elysian Valley CA",
  "Westwood CA", "Brentwood CA", "Pacific Palisades CA",
  "Venice CA", "Mar Vista CA", "Palms CA", "Culver City CA",
  "West Los Angeles CA", "Sawtelle CA",
  "Mid-City CA", "Pico-Robertson CA", "Cheviot Hills CA",
  "Rancho Park CA", "Baldwin Hills CA", "View Park CA",
  "North Hollywood CA", "Studio City CA", "Sherman Oaks CA",
  "Van Nuys CA", "Encino CA", "Tarzana CA", "Woodland Hills CA",
  "Canoga Park CA", "Reseda CA", "Northridge CA", "Granada Hills CA",
  "Sylmar CA", "San Fernando CA", "Mission Hills CA",
  "Panorama City CA", "Arleta CA", "Sunland-Tujunga CA",
  "Shadow Hills CA", "Sun Valley CA", "Lake View Terrace CA",
  "Chatsworth CA", "West Hills CA", "Winnetka CA",
  "Pacoima CA", "Arleta CA",
  "Downtown LA CA", "Financial District Los Angeles CA",
  // LA County — other cities
  "Long Beach CA", "Pasadena CA", "Glendale CA", "Burbank CA",
  "Torrance CA", "Carson CA", "Compton CA", "Inglewood CA",
  "Hawthorne CA", "Gardena CA", "Redondo Beach CA", "Hermosa Beach CA",
  "Manhattan Beach CA", "El Segundo CA", "Lawndale CA",
  "Pomona CA", "Ontario CA", "Rancho Cucamonga CA", "Fontana CA",
  "San Bernardino CA", "Riverside CA", "Moreno Valley CA",
  "Corona CA", "Murrieta CA", "Temecula CA", "Lake Elsinore CA",
  "Alhambra CA", "Monterey Park CA", "Rosemead CA", "El Monte CA",
  "Arcadia CA", "Monrovia CA", "Azusa CA", "Covina CA", "West Covina CA",
  "Diamond Bar CA", "Walnut CA", "Rowland Heights CA",
  "Industry CA", "La Puente CA", "Baldwin Park CA",
  "South Pasadena CA", "San Gabriel CA", "Temple City CA",
  "Whittier CA", "Pico Rivera CA", "Downey CA", "Norwalk CA",
  "Lakewood CA", "Bellflower CA", "Cerritos CA", "Artesia CA",
  "Paramount CA", "Lynwood CA", "South Gate CA", "Huntington Park CA",
  "Bell CA", "Maywood CA", "Bell Gardens CA", "Commerce CA",
  "Montebello CA", "Vernon CA",
  "Malibu CA", "Calabasas CA", "Agoura Hills CA", "Thousand Oaks CA",
  "Simi Valley CA", "Moorpark CA", "Camarillo CA",
  "La Verne CA", "Claremont CA", "Glendora CA", "San Dimas CA",
  "Santa Fe Springs CA", "Pico Rivera CA",
  "Palos Verdes Estates CA", "Rancho Palos Verdes CA",
  "Rolling Hills Estates CA", "Rolling Hills CA",
  "Signal Hill CA", "San Pedro CA", "Wilmington CA",
  "Watts CA", "Florence-Firestone CA",
  // San Diego
  "San Diego CA", "Downtown San Diego CA", "Little Italy San Diego CA",
  "Gaslamp Quarter CA", "Bankers Hill CA", "Hillcrest CA",
  "North Park CA", "South Park CA", "University Heights CA",
  "Normal Heights CA", "Kensington CA", "City Heights CA",
  "El Cerrito CA", "Talmadge CA", "Allied Gardens CA",
  "Mission Hills CA", "Old Town CA", "Mission Valley CA",
  "Mission Beach CA", "Pacific Beach CA", "Bay Park CA",
  "Linda Vista CA", "Clairemont CA", "Bay Ho CA",
  "La Jolla CA", "University City CA", "Mira Mesa CA",
  "Scripps Ranch CA", "Miramar CA", "Sorrento Valley CA",
  "Carmel Valley CA", "Del Mar Heights CA", "Torrey Pines CA",
  "Rancho Bernardo CA", "Rancho Penasquitos CA", "Poway CA",
  "Santee CA", "El Cajon CA", "La Mesa CA", "Spring Valley CA",
  "Lemon Grove CA", "National City CA", "Chula Vista CA",
  "Bonita CA", "Otay Ranch CA",
  "Escondido CA", "San Marcos CA", "Vista CA", "Oceanside CA",
  "Carlsbad CA", "Encinitas CA", "Solana Beach CA", "Del Mar CA",
  // San Francisco Bay Area
  "San Francisco CA", "Downtown San Francisco CA", "SOMA CA",
  "Mission District CA", "Castro CA", "Noe Valley CA", "Bernal Heights CA",
  "Excelsior CA", "Outer Sunset CA", "Inner Sunset CA",
  "Haight-Ashbury CA", "Cole Valley CA", "Twin Peaks CA",
  "Glen Park CA", "West Portal CA", "Forest Hill CA",
  "Ingleside CA", "Visitacion Valley CA", "Portola CA",
  "Bayview CA", "Potrero Hill CA", "Dogpatch CA",
  "Hayes Valley CA", "Tenderloin CA", "Civic Center CA",
  "North Beach CA", "Chinatown CA", "Financial District CA",
  "Embarcadero CA", "Rincon Hill CA", "Treasure Island CA",
  "Marina CA", "Cow Hollow CA", "Pacific Heights CA",
  "Lower Pacific Heights CA", "Japantown CA", "Fillmore CA",
  "Western Addition CA", "Alamo Square CA", "NoPa CA",
  "Richmond District CA", "Presidio Heights CA", "Sea Cliff CA",
  // East Bay
  "Oakland CA", "Downtown Oakland CA", "Uptown Oakland CA",
  "Lake Merritt CA", "Temescal CA", "Rockridge CA", "Grand Lake CA",
  "Montclair CA", "Piedmont CA", "Fruitvale CA", "San Antonio CA",
  "Laurel CA", "Dimond CA", "Glenview CA", "Maxwell Park CA",
  "Berkeley CA", "Downtown Berkeley CA", "North Berkeley CA",
  "South Berkeley CA", "West Berkeley CA", "Elmwood CA",
  "Emeryville CA", "Albany CA", "El Cerrito CA",
  "Richmond CA", "San Pablo CA", "El Sobrante CA",
  "Fremont CA", "Newark CA", "Union City CA", "Hayward CA",
  "San Leandro CA", "Castro Valley CA",
  // South Bay
  "San Jose CA", "Downtown San Jose CA", "Willow Glen CA",
  "Rose Garden CA", "Naglee Park CA", "Alviso CA",
  "Japantown San Jose CA", "Alum Rock CA", "Berryessa CA",
  "North San Jose CA", "Evergreen CA", "Blossom Hill CA",
  "Santa Clara CA", "Sunnyvale CA", "Mountain View CA",
  "Los Altos CA", "Palo Alto CA", "Menlo Park CA",
  "Redwood City CA", "San Mateo CA", "Foster City CA",
  "Burlingame CA", "Millbrae CA", "Daly City CA",
  "South San Francisco CA", "Brisbane CA", "Colma CA",
  "Cupertino CA", "Saratoga CA", "Campbell CA", "Los Gatos CA",
  "Milpitas CA", "Morgan Hill CA", "Gilroy CA",
  "Pleasanton CA", "Livermore CA", "Dublin CA", "San Ramon CA",
  "Danville CA", "Walnut Creek CA", "Concord CA", "Pleasant Hill CA",
  "Martinez CA", "Antioch CA", "Pittsburg CA", "Brentwood CA",
  // North Bay
  "San Rafael CA", "Novato CA", "Petaluma CA", "Santa Rosa CA",
  "Rohnert Park CA", "Cotati CA", "Sebastopol CA", "Windsor CA",
  "Healdsburg CA", "Napa CA", "American Canyon CA", "Vallejo CA",
  "Benicia CA", "Fairfield CA", "Vacaville CA",
  // Sacramento
  "Sacramento CA", "Downtown Sacramento CA", "Midtown Sacramento CA",
  "East Sacramento CA", "Land Park CA", "Curtis Park CA",
  "Oak Park CA", "Tahoe Park CA", "Arden-Arcade CA",
  "Citrus Heights CA", "Rancho Cordova CA", "Elk Grove CA",
  "Folsom CA", "El Dorado Hills CA", "Roseville CA",
  "Rocklin CA", "Lincoln CA", "Auburn CA",
  "Davis CA", "Woodland CA", "West Sacramento CA",
  // Central Valley
  "Fresno CA", "Clovis CA", "Visalia CA", "Tulare CA",
  "Hanford CA", "Bakersfield CA", "Stockton CA", "Modesto CA",
  "Merced CA", "Madera CA", "Turlock CA",
];
