// Washington State — all major cities, towns and metro neighbourhoods
export const SEATTLE_NEIGHBORHOODS = [
  // Seattle proper — neighbourhoods
  "Capitol Hill Seattle",
  "Belltown Seattle",
  "South Lake Union Seattle",
  "Queen Anne Seattle",
  "Fremont Seattle",
  "Ballard Seattle",
  "West Seattle Seattle",
  "Columbia City Seattle",
  "Beacon Hill Seattle",
  "First Hill Seattle",
  "Pioneer Square Seattle",
  "Downtown Seattle",
  "Eastlake Seattle",
  "Madrona Seattle",
  "Madison Park Seattle",
  "Green Lake Seattle",
  "Wallingford Seattle",
  "University District Seattle",
  "Northgate Seattle",
  "Phinney Ridge Seattle",
  "Ravenna Seattle",
  "Maple Leaf Seattle",
  "Lake City Seattle",
  "Laurelhurst Seattle",
  "Montlake Seattle",
  "Sand Point Seattle",
  "View Ridge Seattle",
  "Bryant Seattle",
  "Wedgwood Seattle",
  "Seward Park Seattle",
  "Mount Baker Seattle",
  "Georgetown Seattle",
  "SoDo Seattle",
  "Interbay Seattle",
  "Magnolia Seattle",
  "Crown Hill Seattle",
  "Bitter Lake Seattle",
  "Haller Lake Seattle",
  "Pinehurst Seattle",
  "Olympic Hills Seattle",
  "Rainier Beach Seattle",
  "Rainier Valley Seattle",
  "Othello Seattle",
  "Brighton Seattle",
  "Dunlap Seattle",
  "High Point Seattle",
  "South Park Seattle",
  "Delridge Seattle",
  "Burien Seattle",
  "White Center Seattle",

  // Eastside — Bellevue
  "Bellevue WA",
  "Downtown Bellevue WA",
  "Crossroads Bellevue WA",
  "Eastgate Bellevue WA",
  "Newport Hills Bellevue WA",
  "Somerset Bellevue WA",
  "West Bellevue WA",
  "Medina WA",

  // Eastside — Kirkland / Redmond
  "Kirkland WA",
  "Juanita WA",
  "Totem Lake WA",
  "Redmond WA",
  "Overlake WA",
  "Education Hill Redmond WA",
  "Sammamish WA",
  "Issaquah WA",
  "North Bend WA",
  "Snoqualmie WA",

  // North King County / Snohomish
  "Shoreline WA",
  "Lake Forest Park WA",
  "Kenmore WA",
  "Bothell WA",
  "Woodinville WA",
  "Duvall WA",
  "Monroe WA",
  "Everett WA",
  "North Everett WA",
  "South Everett WA",
  "Mukilteo WA",
  "Lynnwood WA",
  "Mountlake Terrace WA",
  "Edmonds WA",
  "Marysville WA",
  "Arlington WA",
  "Stanwood WA",
  "Mount Vernon WA",
  "Burlington WA",
  "Anacortes WA",
  "Bellingham WA",
  "Ferndale WA",
  "Blaine WA",

  // South King County
  "Renton WA",
  "Newcastle WA",
  "Kent WA",
  "Auburn WA",
  "Federal Way WA",
  "Des Moines WA",
  "SeaTac WA",
  "Tukwila WA",
  "Covington WA",
  "Maple Valley WA",
  "Black Diamond WA",
  "Enumclaw WA",

  // Pierce County — Tacoma
  "Tacoma WA",
  "Downtown Tacoma WA",
  "North End Tacoma WA",
  "Proctor Tacoma WA",
  "Stadium District Tacoma WA",
  "Hilltop Tacoma WA",
  "South End Tacoma WA",
  "East Side Tacoma WA",
  "Lakewood WA",
  "University Place WA",
  "Puyallup WA",
  "Sumner WA",
  "Bonney Lake WA",
  "Gig Harbor WA",
  "Fircrest WA",
  "Steilacoom WA",
  "DuPont WA",

  // Thurston County — Olympia
  "Olympia WA",
  "Lacey WA",
  "Tumwater WA",
  "Yelm WA",

  // Clark County — Vancouver WA
  "Vancouver WA",
  "Downtown Vancouver WA",
  "Hazel Dell WA",
  "Salmon Creek WA",
  "Felida WA",
  "Camas WA",
  "Washougal WA",
  "Battle Ground WA",

  // Eastern Washington — Spokane
  "Spokane WA",
  "Spokane Valley WA",
  "North Spokane WA",
  "South Hill WA",
  "Cheney WA",
  "Liberty Lake WA",
  "Post Falls WA",

  // Eastern Washington — Tri-Cities
  "Kennewick WA",
  "Richland WA",
  "Pasco WA",
  "West Richland WA",

  // Central Washington — Yakima / Wenatchee
  "Yakima WA",
  "Selah WA",
  "Union Gap WA",
  "Wenatchee WA",
  "East Wenatchee WA",

  // Kitsap / Olympic Peninsula
  "Bremerton WA",
  "Silverdale WA",
  "Poulsbo WA",
  "Port Orchard WA",
  "Port Angeles WA",
  "Sequim WA",
];
