// Seattle metro neighbourhoods — crawled in order
export const SEATTLE_NEIGHBORHOODS = [
  "Capitol Hill Seattle",
  "Belltown Seattle",
  "South Lake Union Seattle",
  "Queen Anne Seattle",
  "Fremont Seattle",
  "Ballard Seattle",
  "West Seattle Seattle",
  "Columbia City Seattle",
  "Beacon Hill Seattle",
  "First Hill Seattle",
  "Pioneer Square Seattle",
  "Downtown Seattle",
  "Eastlake Seattle",
  "Madrona Seattle",
  "Madison Park Seattle",
  "Green Lake Seattle",
  "Wallingford Seattle",
  "University District Seattle",
  "Northgate Seattle",
  "Redmond WA",
  "Bellevue WA",
  "Kirkland WA",
  "Mercer Island WA",
  "Renton WA",
  "Bothell WA",
  "Issaquah WA",
  "Shoreline WA",
];
